EigenPairs

In [25]:
import numpy as np
data = [[3, 1], [2, 2]]
w, v = np.linalg.eig(data)
# print eigenvalue and eigenvector
print(w, v)
# for making sure that eigenvalue and eigenvector is correct we have to just check this condition Av = λv
print(np.allclose(np.dot(data, v[:, 0]), np.dot(w[0], v[:, 0])))

[4. 1.] [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
4.0 1.0
[0.70710678 0.70710678]
[2.82842712 2.82842712]
True


In [49]:
a = np.array([[1, 2,3], [3, 4,5],[5,6,7]])
print(a.T)
print(a.transpose())

[[1 3 5]
 [2 4 6]
 [3 5 7]]
[[1 3 5]
 [2 4 6]
 [3 5 7]]


In [44]:
b = np.array([[1,2,3],[3,4,5],[5,4,3],[0,2,4],[1,3,5]]) 
eigvals, eigvecs = np.linalg.eig(b @ b.T)
print(np.allclose(np.dot(b @ b.T,eigvecs[:,0]),np.dot(eigvals[0],eigvecs[:,0])))

[[ 0.29769568  0.94131607 -0.15906393 -0.78673469  0.17238272]
 [ 0.57050856 -0.17481584  0.0332003  -0.09936245  0.08563818]
 [ 0.52074297 -0.04034212  0.73585663  0.21995086 -0.19713125]
 [ 0.32257847 -0.18826321 -0.5103921   0.56795623 -0.78393509]
 [ 0.45898491 -0.21515796 -0.41425998 -0.01493222  0.55635901]]
True
