Implement the logistic regression model. 
The gradient of the cross-entropy loss for a single training example is as follows: 
$$ \nabla_w \mathcal{L}(\hat{y}_i, \hat{y_i}) = (\hat{y}_i - y_i) \mathbf{x_i} $$
with $\hat{y}_i = \frac{1}{1 + \exp{-\mathbf{w^T x}}}$.

In [1]:
import numpy as np
import sklearn.datasets
from numpy.linalg import inv
import sklearn.metrics
import sklearn.linear_model
from tqdm.notebook import tqdm
import math

In [2]:
class LogisticClassifier():
    def __init__(self) -> None:
        self.w = None

    def _add_constant(self, X: np.ndarray) -> np.ndarray:
        """Add a constant column to a matrix.

        Args:
            X (np.ndarray): Original data matrix

        Returns:
            np.ndarray: Original data matrix with concatenated column of all ones.
        """
        return np.hstack((X, np.ones((len(X), 1))))

    def fit(
        self,
        X: np.ndarray, 
        y: np.ndarray, 
        learning_rate: float=1e-3, 
        n_epochs: int=500, 
        random_state: int=42,
        ) -> None:
        """Fit the parameters of the model to the data with gradient descent.

        Args:
            X (np.ndarray): features
            y (np.ndarray): targets
            learning_rate (float): step size of gradient descent
            n_epochs (int): number of parameter updates
            random_state (int): seed for reproducibility
        """
        # initialize randomly
        rng = np.random.default_rng(random_state)
        self.w = rng.standard_normal(size=(X.shape[1] + 1, ))  # +1 for bias
        #print(self.w.shape)

        # gradient descent
        for _ in tqdm(range(n_epochs)):
            self.w = self.w - learning_rate * self._gradient(X, y)
            if np.isnan(self.w).sum() > 0:
                raise ValueError("Weights have diverged", self.w)

    def _gradient(self, X: np.ndarray, y: np.ndarray):
        return sum([(yhat - y) * x for x, y, yhat in zip(self._add_constant(X), y, self.predict_proba(X))])

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Use parameters to predict values

        Args:
            X (np.ndarray): features

        Returns:
            np.ndarray: predicted probablities
        """
        X = self._add_constant(X) 
        probas = []
        for x in X:
            probas.append(1 / (1 + np.exp (- self.w.T @ x)))
        probas = np.array(probas)
        return probas



X, y = sklearn.datasets.make_classification(n_samples=1000, random_state=13)

model = LogisticClassifier()
model.fit(X, y, n_epochs=100, learning_rate=1e-3, random_state=0)

skl_model = sklearn.linear_model.LogisticRegression(random_state=0)
skl_model.fit(X, y)

sklearn.metrics.roc_auc_score(y, model.predict_proba(X)), sklearn.metrics.roc_auc_score(y, skl_model.predict_proba(X)[:, 1])

#model.predict_proba(X)

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [33]:
x = np.arange(36).reshape(-1, 9)
print(x)
print(x.shape[2])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


IndexError: tuple index out of range