In [1]:
import torch
import torch.nn.functional as F

In [6]:
X = torch.tensor([[0, 0, 1], [0, 1, 0], [1, 0, 0],], dtype=torch.float)
W_Q = torch.tensor([[2, 1], [0, 1], [1, -1],], dtype=torch.float)
W_K = torch.tensor([[0, 1], [1, 1], [3, 1],], dtype=torch.float)
W_V = torch.tensor([[-1, 1], [3, 0], [-3, 0],], dtype=torch.float)
Q = X @ W_Q
K = X @ W_K
V = X @ W_V
print(Q)
print(K)
print(V)


tensor([[ 1., -1.],
        [ 0.,  1.],
        [ 2.,  1.]])
tensor([[3., 1.],
        [1., 1.],
        [0., 1.]])
tensor([[-3.,  0.],
        [ 3.,  0.],
        [-1.,  1.]])


In [23]:
d = Q @ K.T
print(d)
x = 1/torch.sqrt(torch.tensor(2)) * Q @ K.T
print(x)
a =F.softmax(1/torch.sqrt(torch.tensor(2)) * Q @ K.T, dim=1)
print(a)
Z = F.softmax(1/torch.sqrt(torch.tensor(2)) * Q @ K.T, dim=1) @ V

tensor([[ 1.4142,  0.0000, -0.7071],
        [ 0.7071,  0.7071,  0.7071],
        [ 4.9497,  2.1213,  0.7071]])
tensor([[0.7337, 0.1784, 0.0879],
        [0.3333, 0.3333, 0.3333],
        [0.9316, 0.0551, 0.0134]])
